- name: Run App container
  community.docker.docker_container:
    name: simple-api
    image: smaileyyy/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    env:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"
    networks:
      - name: network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python