name: Deploy on new Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Ou déclenchement sur un tag spécifique

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable SSH host key checking
        run: |
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml